version: '3.7'

services:

  server:
    build:
      context: .
    ports:
      - "80:80"
    volumes:
      - ./index.html:/data/www/index.html
      - ./images:/data/images
      - ./javascript:/data/javascript
